expose:
  type: nodePort
  tls:
    enabled: false
  nodePort:
    name: nginx
    ports:
      http:
        nodePort: 30003
      https:
        nodePort: 30004
  ingress:
    hosts:
      core: harbor.local

externalURL: https://harbor.techlearning.me

harborAdminPassword: "admin123"

database:
  type: internal
  internal:
    password: "admin123"
  external:
    enabled: false

redis:
  type: internal

core:
  replicas: 1
  extraVolumes:
    - name: harbor-ca
      configMap:
        name: harbor-ca
  extraVolumeMounts:
    - name: harbor-ca
      mountPath: /usr/local/share/ca-certificates/harbor
      readOnly: true
  extraEnv:
    - name: HARBOR_INIT_CMD
      value: "update-ca-certificates && /harbor/start.sh"

portal:
  replicas: 1

jobservice:
  replicas: 1
  extraVolumes:
    - name: harbor-ca
      configMap:
        name: harbor-ca
  extraVolumeMounts:
    - name: harbor-ca
      mountPath: /usr/local/share/ca-certificates/harbor
      readOnly: true
  extraEnv:
    - name: HARBOR_INIT_CMD
      value: "update-ca-certificates && /harbor/start.sh"

registry:
  replicas: 1
  persistence:
    enabled: false   # Disable persistent volume for testing

chartmuseum:
  enabled: false     # Optional: disable if not needed

clair:
  enabled: false     # Optional: disable vulnerability scanning (faster setup)

notary:
  enabled: false

trivy:
  enabled: false     # Disable for dev speed

metrics:
  enabled: false

persistence:
  enabled: false     # Disable PVCs for local testing

logLevel: debug
