apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafdrop
  namespace: ns-kafka
  labels:
    app: kafdrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: KAFKA_BROKERCONNECT
              value: "kafka-0.kafka-headless:9092,kafka-1.kafka-headless:9092,kafka-2.kafka-headless:9092"
            - name: JVM_OPTS
              value: "-Xms64M -Xmx256M"
            - name: SERVER_PORT
              value: "9000"
            - name: SERVER_SERVLET_CONTEXTPATH
              value: "/"
---
apiVersion: v1
kind: Service
metadata:
  name: kafdrop
  namespace: ns-kafka
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: kafdrop
