apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: ns-kafka
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: ns-kafka
spec:
  serviceName: kafka-headless
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest
          command:
            - sh
            - -c
            - |
              export BROKER_ID=${HOSTNAME##*-}
              export KAFKA_ZOOKEEPER_CONNECT=zookeeper-headless:2181

              # Define both internal and external listeners
              export KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094
              export KAFKA_ADVERTISED_LISTENERS=INTERNAL://${HOSTNAME}.kafka-headless.ns-kafka.svc.cluster.local:9092,EXTERNAL://${HOSTNAME}.techlearning.me:9094
              export KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
              export KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL

              echo "listeners=${KAFKA_LISTENERS}" >> /opt/kafka/config/server.properties
              echo "advertised.listeners=${KAFKA_ADVERTISED_LISTENERS}" >> /opt/kafka/config/server.properties
              echo "listener.security.protocol.map=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}" >> /opt/kafka/config/server.properties
              echo "inter.broker.listener.name=${KAFKA_INTER_BROKER_LISTENER_NAME}" >> /opt/kafka/config/server.properties
    
              # Update Kafka configuration file
              sed -i "s|^zookeeper.connect=.*|zookeeper.connect=${KAFKA_ZOOKEEPER_CONNECT}|" /opt/kafka/config/server.properties
              sed -i "s|^broker.id=.*|broker.id=${BROKER_ID}|" /opt/kafka/config/server.properties

              exec /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties

          ports:
            - containerPort: 9092
              name: internal
            - containerPort: 9094
              name: external

          env:
            - name: KAFKA_LISTENERS
              value: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9094"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://$(HOSTNAME).kafka-headless.ns-kafka.svc.cluster.local:9092,EXTERNAL://$(HOSTNAME).techlearning.me:9094"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-headless.ns-kafka.svc.cluster.local:2181"

          volumeMounts:
            - name: data
              mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi